USE [master]
GO

/****** Object:  Database [DW]    Script Date: 2/21/2021 9:12:13 PM ******/
CREATE DATABASE [DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DW_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DW] SET ARITHABORT OFF 
GO

ALTER DATABASE [DW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DW] SET RECOVERY FULL 
GO

ALTER DATABASE [DW] SET  MULTI_USER 
GO

ALTER DATABASE [DW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DW] SET  READ_WRITE 
GO

