USE [master]
GO

/****** Object:  Database [HR]    Script Date: 2/21/2021 9:12:42 PM ******/
CREATE DATABASE [HR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HR.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HR_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HR] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HR] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HR] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HR] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HR] SET ARITHABORT OFF 
GO

ALTER DATABASE [HR] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HR] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HR] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HR] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HR] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HR] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HR] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HR] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HR] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HR] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HR] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HR] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HR] SET RECOVERY FULL 
GO

ALTER DATABASE [HR] SET  MULTI_USER 
GO

ALTER DATABASE [HR] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HR] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HR] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HR] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HR] SET  READ_WRITE 
GO

